#############################################################################
# Makefile for building: Robotics2012.app/Contents/MacOS/Robotics2012
# Generated by qmake (2.01a) (Qt 4.8.1) on: Tue Aug 7 00:49:59 2012
# Project:  Robotics2012.pro
# Template: app
# Command: /Users/redbear/Lib/QtSDK/Desktop/Qt/4.8.1/gcc/bin/qmake -spec ../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++ CONFIG+=declarative_debug -o Makefile Robotics2012.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++ -I. -I../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtCore.framework/Versions/4/Headers -I../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/include/QtCore -I../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtGui.framework/Versions/4/Headers -I../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/include/QtGui -I../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtOpenGL.framework/Versions/4/Headers -I../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/include/QtOpenGL -I../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/include -I/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/System/Library/Frameworks/AGL.framework/Headers -I. -I. -F/Users/redbear/Lib/QtSDK/Desktop/Qt/4.8.1/gcc/lib
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/Users/redbear/Lib/QtSDK/Desktop/Qt/4.8.1/gcc/lib -L/Users/redbear/Lib/QtSDK/Desktop/Qt/4.8.1/gcc/lib -framework QtOpenGL -L/usr/local/pgsql/lib -L/tmp/qt-stuff-85167/source/qt-everywhere-opensource-src-4.8.1/Desktop/Qt/4.8.1/gcc/lib -F/tmp/qt-stuff-85167/source/qt-everywhere-opensource-src-4.8.1/Desktop/Qt/4.8.1/gcc/lib -framework QtGui -framework QtCore -framework OpenGL -framework AGL 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /Users/redbear/Lib/QtSDK/Desktop/Qt/4.8.1/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		glwidget.cpp \
		_model.cpp \
		_draw_gl.cpp \
		_calculator.cpp moc_mainwindow.cpp \
		moc_glwidget.cpp
OBJECTS       = main.o \
		mainwindow.o \
		glwidget.o \
		_model.o \
		_draw_gl.o \
		_calculator.o \
		moc_mainwindow.o \
		moc_glwidget.o
DIST          = ../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/mac.conf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-macx.conf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-macx.conf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_pre.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/dwarf2.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/debug.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_post.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/x86_64.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/objective_c.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/declarative_debug.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/opengl.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/rez.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/sdk.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf \
		Robotics2012.pro
QMAKE_TARGET  = Robotics2012
DESTDIR       = 
TARGET        = Robotics2012.app/Contents/MacOS/Robotics2012

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile Robotics2012.app/Contents/PkgInfo Robotics2012.app/Contents/Resources/empty.lproj Robotics2012.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) Robotics2012.app/Contents/MacOS/ || $(MKDIR) Robotics2012.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Robotics2012.pro  ../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++/qmake.conf ../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/mac.conf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-macx.conf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-macx.conf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_pre.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/dwarf2.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/debug.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_post.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/x86_64.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/objective_c.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/declarative_debug.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/opengl.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/rez.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/sdk.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf \
		../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf \
		/Users/redbear/Lib/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtOpenGL.framework/QtOpenGL.prl \
		/Users/redbear/Lib/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtGui.framework/QtGui.prl \
		/Users/redbear/Lib/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec ../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++ CONFIG+=declarative_debug -o Makefile Robotics2012.pro
../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf:
../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/mac.conf:
../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf:
../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-macx.conf:
../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf:
../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-macx.conf:
../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri:
../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri:
../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf:
../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf:
../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf:
../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf:
../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_pre.prf:
../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/dwarf2.prf:
../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/debug.prf:
../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf:
../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_post.prf:
../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/x86_64.prf:
../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/objective_c.prf:
../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/declarative_debug.prf:
../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf:
../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf:
../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/opengl.prf:
../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf:
../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf:
../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/rez.prf:
../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/sdk.prf:
../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf:
../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf:
../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf:
../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf:
../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf:
/Users/redbear/Lib/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtOpenGL.framework/QtOpenGL.prl:
/Users/redbear/Lib/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtGui.framework/QtGui.prl:
/Users/redbear/Lib/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++ CONFIG+=declarative_debug -o Makefile Robotics2012.pro

Robotics2012.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) Robotics2012.app/Contents || $(MKDIR) Robotics2012.app/Contents 
	@$(DEL_FILE) Robotics2012.app/Contents/PkgInfo
	@echo "APPL????" >Robotics2012.app/Contents/PkgInfo
Robotics2012.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) Robotics2012.app/Contents/Resources || $(MKDIR) Robotics2012.app/Contents/Resources 
	@touch Robotics2012.app/Contents/Resources/empty.lproj
	
Robotics2012.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) Robotics2012.app/Contents || $(MKDIR) Robotics2012.app/Contents 
	@$(DEL_FILE) Robotics2012.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,Robotics2012,g" -e "s,@TYPEINFO@,????,g" ../../Lib/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++/Info.plist.app >Robotics2012.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/Robotics20121.0.0 || $(MKDIR) .tmp/Robotics20121.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Robotics20121.0.0/ && $(COPY_FILE) --parents mainwindow.h glwidget.h _gl.h .tmp/Robotics20121.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp glwidget.cpp _model.cpp _draw_gl.cpp _calculator.cpp .tmp/Robotics20121.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/Robotics20121.0.0/ && (cd `dirname .tmp/Robotics20121.0.0` && $(TAR) Robotics20121.0.0.tar Robotics20121.0.0 && $(COMPRESS) Robotics20121.0.0.tar) && $(MOVE) `dirname .tmp/Robotics20121.0.0`/Robotics20121.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Robotics20121.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r Robotics2012.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_glwidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_glwidget.cpp
moc_mainwindow.cpp: mainwindow.h
	/Users/redbear/Lib/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ mainwindow.h -o moc_mainwindow.cpp

moc_glwidget.cpp: _gl.h \
		glwidget.h
	/Users/redbear/Lib/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ glwidget.h -o moc_glwidget.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		glwidget.h \
		_gl.h
	/Users/redbear/Lib/QtSDK/Desktop/Qt/4.8.1/gcc/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

glwidget.o: glwidget.cpp glwidget.h \
		_gl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glwidget.o glwidget.cpp

_model.o: _model.cpp _gl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o _model.o _model.cpp

_draw_gl.o: _draw_gl.cpp _gl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o _draw_gl.o _draw_gl.cpp

_calculator.o: _calculator.cpp _gl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o _calculator.o _calculator.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_glwidget.o: moc_glwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_glwidget.o moc_glwidget.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

